### ISSUE TITLE
Lars laver Css

### ISSUE THREAD

**Issue by Chrstjan** [Chrstjan/Gruppe3-Opgave#7]
Lars laver en images mappe .
 linker vores sider sammen i index siden og laver Css

**Comment by LarsKarlsen82** [comment]
Jeg laver css og linker alles html profil sider sammen i en nav bar

**Comment by LarsKarlsen82** [comment]
CSS lavet, men det er længe siden jeg har leget med CSS, så det er desværre lappeløsninger der og der :P
